version: '3'

services:
  # 改镜像会暴露出自身的 `header` 信息
  whoami:
    image: containous/whoami
    labels:
      # 设置Host 为 whoami.docker.localhost 进行域名访问
      - "traefik.http.routers.whoami.rule=Host(`whoami.shanyue.local`)"

# 使用已存在的 traefik 的 network
networks:
  default:
    external:
      name: vite-project_default

# version: '3'

# services:
#   traefik:
#     image: traefik:v2.5
#     command: --api.insecure=true --providers.docker
#     ports:
#       - "80:80"
#       - "8080:8080"
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock

# version: "3"
# services:
#   simple:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - 4000:80
# version: "3"
# services:
#   node-app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - 3000:3000
  # nginx-app:
  #   build:
  #     context: .
  #     dockerfile: nginx.Dockerfile
  #   ports:
  #     - 4000:80