# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: install
      uses: borales/actions-yarn@v3.0.0
      with:
        cmd: install
    - name: build
      uses: borales/actions-yarn@v3.0.0
      with:
        cmd: build
    # 打包镜像推送到阿里云容器镜像服务
    - name: Build the Docker image
      run: |
        docker login --username=${{ secrets.DOCKER_USERNAME }} registry.cn-hangzhou.aliyuncs.com --password=${{ secrets.DOCKER_PASSWORD }}
        docker build -t github-action:latest .
        docker tag github-action registry.cn-hangzhou.aliyuncs.com/chase-test/github-action:latest
        docker push registry.cn-hangzhou.aliyuncs.com/chase-test/github-action:latest
    
#      uses: actions/setup-node@v3
#      with:
#        node-version: ${{ matrix.node-version }}
#        cache: 'npm'
#    - run: npm install
#    - run: npm run build --if-present
#    - run: npm run build
